List<Map> weightUnits = [
  {"id": 1, "name": "Tonne", "unit": "tonne"},
  {"id": 2, "name": "Kilogram", "unit": "kg"},
  {"id": 3, "name": "Gram", "unit": "g"},
  {"id": 4, "name": "Milligram", "unit": "mg"},
  {"id": 5, "name": "Microgram", "unit": "microgram"},
  {"id": 6, "name": "Imperial Tonne", "unit": "imptonne"},
  {"id": 7, "name": "US Tonne", "unit": "ustonne"},
  {"id": 8, "name": "Stone", "unit": "stone"},
  {"id": 9, "name": "Pound", "unit": "pound"},
  {"id": 10, "name": "Ounce", "unit": "ounce"},
  {"id": 11, "name": "Hectogram", "unit": "hg"},
  {"id": 12, "name": "Decigram", "unit": "dg"},
  {"id": 13, "name": "Centigram", "unit": "cg"},
  {"id": 14, "name": "Carat", "unit": "carat"},
  {"id": 15, "name": "Grain", "unit": "grain"},
];
